# Generated by Django 4.2 on 2023-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="money_to_pay",
            field=models.IntegerField(),
        ),
    ]
