# Generated by Django 4.2 on 2023-04-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.IntegerField(),
        ),
    ]
